name: Build Combined Distribution

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # allow the action to upload release assets

    steps:
      # 1) Checkout this repo (core)
      - name: Checkout core
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: core

      # 2) Fetch latest release tag from splitphp/starter
      - name: Get latest starter release
        id: starter
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { data } = await github.rest.repos.getLatestRelease({
              owner: 'splitphp',
              repo:  'starter'
            });
            return data.tag_name;

      # 3) Checkout splitphp/starter at that tag into ./starter
      - name: Checkout starter
        uses: actions/checkout@v3
        with:
          repository: splitphp/starter
          token:      ${{ secrets.GITHUB_TOKEN }}
          ref:        ${{ steps.starter.outputs.result }}
          path:       starter

      # 4) Assemble dist/ folder
      - name: Assemble distribution folder
        run: |
          mkdir -p dist/core
          # empacota starter, respeitando export-ignore
          git -C starter archive HEAD --format=tar | tar -x -C dist/
          # empacota core, respeitando export-ignore
          git -C core archive HEAD --format=tar | tar -x -C dist/core/

      # 5) Zip it up
      - name: Zip distribution
        run: |
          cd dist
          zip -r "../splitphp-distribution-${{ github.event.release.tag_name }}.zip" ./*

      # 6) Upload the ZIP back to the Release
      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          files: splitphp-distribution-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
